# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/davidrussell/catkin_ws/src/physicsSimSwitching

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/davidrussell/catkin_ws/src/physicsSimSwitching

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davidrussell/catkin_ws/src/physicsSimSwitching/CMakeFiles /home/davidrussell/catkin_ws/src/physicsSimSwitching/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davidrussell/catkin_ws/src/physicsSimSwitching/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named clean_test_results

# Build rule for target.
clean_test_results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_test_results
.PHONY : clean_test_results

# fast build rule for target.
clean_test_results/fast:
	$(MAKE) -f CMakeFiles/clean_test_results.dir/build.make CMakeFiles/clean_test_results.dir/build
.PHONY : clean_test_results/fast

#=============================================================================
# Target rules for targets named download_extra_data

# Build rule for target.
download_extra_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 download_extra_data
.PHONY : download_extra_data

# fast build rule for target.
download_extra_data/fast:
	$(MAKE) -f CMakeFiles/download_extra_data.dir/build.make CMakeFiles/download_extra_data.dir/build
.PHONY : download_extra_data/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named _catkin_empty_exported_target

# Build rule for target.
_catkin_empty_exported_target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _catkin_empty_exported_target
.PHONY : _catkin_empty_exported_target

# fast build rule for target.
_catkin_empty_exported_target/fast:
	$(MAKE) -f CMakeFiles/_catkin_empty_exported_target.dir/build.make CMakeFiles/_catkin_empty_exported_target.dir/build
.PHONY : _catkin_empty_exported_target/fast

#=============================================================================
# Target rules for targets named physicsSimSwitching

# Build rule for target.
physicsSimSwitching: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 physicsSimSwitching
.PHONY : physicsSimSwitching

# fast build rule for target.
physicsSimSwitching/fast:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/build
.PHONY : physicsSimSwitching/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f gtest/googlemock/CMakeFiles/gmock_main.dir/build.make gtest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f gtest/googlemock/CMakeFiles/gmock.dir/build.make gtest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest_main.dir/build.make gtest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/googletest/CMakeFiles/gtest.dir/build.make gtest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/main.cpp.s
.PHONY : main.cpp.s

modelTranslator/doublePendulum.o: modelTranslator/doublePendulum.cpp.o

.PHONY : modelTranslator/doublePendulum.o

# target to build an object file
modelTranslator/doublePendulum.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/doublePendulum.cpp.o
.PHONY : modelTranslator/doublePendulum.cpp.o

modelTranslator/doublePendulum.i: modelTranslator/doublePendulum.cpp.i

.PHONY : modelTranslator/doublePendulum.i

# target to preprocess a source file
modelTranslator/doublePendulum.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/doublePendulum.cpp.i
.PHONY : modelTranslator/doublePendulum.cpp.i

modelTranslator/doublePendulum.s: modelTranslator/doublePendulum.cpp.s

.PHONY : modelTranslator/doublePendulum.s

# target to generate assembly for a file
modelTranslator/doublePendulum.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/doublePendulum.cpp.s
.PHONY : modelTranslator/doublePendulum.cpp.s

modelTranslator/modelTranslator.o: modelTranslator/modelTranslator.cpp.o

.PHONY : modelTranslator/modelTranslator.o

# target to build an object file
modelTranslator/modelTranslator.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/modelTranslator.cpp.o
.PHONY : modelTranslator/modelTranslator.cpp.o

modelTranslator/modelTranslator.i: modelTranslator/modelTranslator.cpp.i

.PHONY : modelTranslator/modelTranslator.i

# target to preprocess a source file
modelTranslator/modelTranslator.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/modelTranslator.cpp.i
.PHONY : modelTranslator/modelTranslator.cpp.i

modelTranslator/modelTranslator.s: modelTranslator/modelTranslator.cpp.s

.PHONY : modelTranslator/modelTranslator.s

# target to generate assembly for a file
modelTranslator/modelTranslator.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/modelTranslator/modelTranslator.cpp.s
.PHONY : modelTranslator/modelTranslator.cpp.s

physicsSimulators/MuJoCoHelper.o: physicsSimulators/MuJoCoHelper.cpp.o

.PHONY : physicsSimulators/MuJoCoHelper.o

# target to build an object file
physicsSimulators/MuJoCoHelper.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/MuJoCoHelper.cpp.o
.PHONY : physicsSimulators/MuJoCoHelper.cpp.o

physicsSimulators/MuJoCoHelper.i: physicsSimulators/MuJoCoHelper.cpp.i

.PHONY : physicsSimulators/MuJoCoHelper.i

# target to preprocess a source file
physicsSimulators/MuJoCoHelper.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/MuJoCoHelper.cpp.i
.PHONY : physicsSimulators/MuJoCoHelper.cpp.i

physicsSimulators/MuJoCoHelper.s: physicsSimulators/MuJoCoHelper.cpp.s

.PHONY : physicsSimulators/MuJoCoHelper.s

# target to generate assembly for a file
physicsSimulators/MuJoCoHelper.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/MuJoCoHelper.cpp.s
.PHONY : physicsSimulators/MuJoCoHelper.cpp.s

physicsSimulators/bulletHelper.o: physicsSimulators/bulletHelper.cpp.o

.PHONY : physicsSimulators/bulletHelper.o

# target to build an object file
physicsSimulators/bulletHelper.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/bulletHelper.cpp.o
.PHONY : physicsSimulators/bulletHelper.cpp.o

physicsSimulators/bulletHelper.i: physicsSimulators/bulletHelper.cpp.i

.PHONY : physicsSimulators/bulletHelper.i

# target to preprocess a source file
physicsSimulators/bulletHelper.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/bulletHelper.cpp.i
.PHONY : physicsSimulators/bulletHelper.cpp.i

physicsSimulators/bulletHelper.s: physicsSimulators/bulletHelper.cpp.s

.PHONY : physicsSimulators/bulletHelper.s

# target to generate assembly for a file
physicsSimulators/bulletHelper.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/bulletHelper.cpp.s
.PHONY : physicsSimulators/bulletHelper.cpp.s

physicsSimulators/physicsSimulator.o: physicsSimulators/physicsSimulator.cpp.o

.PHONY : physicsSimulators/physicsSimulator.o

# target to build an object file
physicsSimulators/physicsSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/physicsSimulator.cpp.o
.PHONY : physicsSimulators/physicsSimulator.cpp.o

physicsSimulators/physicsSimulator.i: physicsSimulators/physicsSimulator.cpp.i

.PHONY : physicsSimulators/physicsSimulator.i

# target to preprocess a source file
physicsSimulators/physicsSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/physicsSimulator.cpp.i
.PHONY : physicsSimulators/physicsSimulator.cpp.i

physicsSimulators/physicsSimulator.s: physicsSimulators/physicsSimulator.cpp.s

.PHONY : physicsSimulators/physicsSimulator.s

# target to generate assembly for a file
physicsSimulators/physicsSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/physicsSimulators/physicsSimulator.cpp.s
.PHONY : physicsSimulators/physicsSimulator.cpp.s

stdInclude/stdInclude.o: stdInclude/stdInclude.cpp.o

.PHONY : stdInclude/stdInclude.o

# target to build an object file
stdInclude/stdInclude.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/stdInclude/stdInclude.cpp.o
.PHONY : stdInclude/stdInclude.cpp.o

stdInclude/stdInclude.i: stdInclude/stdInclude.cpp.i

.PHONY : stdInclude/stdInclude.i

# target to preprocess a source file
stdInclude/stdInclude.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/stdInclude/stdInclude.cpp.i
.PHONY : stdInclude/stdInclude.cpp.i

stdInclude/stdInclude.s: stdInclude/stdInclude.cpp.s

.PHONY : stdInclude/stdInclude.s

# target to generate assembly for a file
stdInclude/stdInclude.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/stdInclude/stdInclude.cpp.s
.PHONY : stdInclude/stdInclude.cpp.s

visualizer/visualizer.o: visualizer/visualizer.cpp.o

.PHONY : visualizer/visualizer.o

# target to build an object file
visualizer/visualizer.cpp.o:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/visualizer/visualizer.cpp.o
.PHONY : visualizer/visualizer.cpp.o

visualizer/visualizer.i: visualizer/visualizer.cpp.i

.PHONY : visualizer/visualizer.i

# target to preprocess a source file
visualizer/visualizer.cpp.i:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/visualizer/visualizer.cpp.i
.PHONY : visualizer/visualizer.cpp.i

visualizer/visualizer.s: visualizer/visualizer.cpp.s

.PHONY : visualizer/visualizer.s

# target to generate assembly for a file
visualizer/visualizer.cpp.s:
	$(MAKE) -f CMakeFiles/physicsSimSwitching.dir/build.make CMakeFiles/physicsSimSwitching.dir/visualizer/visualizer.cpp.s
.PHONY : visualizer/visualizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... tests"
	@echo "... clean_test_results"
	@echo "... download_extra_data"
	@echo "... doxygen"
	@echo "... _catkin_empty_exported_target"
	@echo "... physicsSimSwitching"
	@echo "... run_tests"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modelTranslator/doublePendulum.o"
	@echo "... modelTranslator/doublePendulum.i"
	@echo "... modelTranslator/doublePendulum.s"
	@echo "... modelTranslator/modelTranslator.o"
	@echo "... modelTranslator/modelTranslator.i"
	@echo "... modelTranslator/modelTranslator.s"
	@echo "... physicsSimulators/MuJoCoHelper.o"
	@echo "... physicsSimulators/MuJoCoHelper.i"
	@echo "... physicsSimulators/MuJoCoHelper.s"
	@echo "... physicsSimulators/bulletHelper.o"
	@echo "... physicsSimulators/bulletHelper.i"
	@echo "... physicsSimulators/bulletHelper.s"
	@echo "... physicsSimulators/physicsSimulator.o"
	@echo "... physicsSimulators/physicsSimulator.i"
	@echo "... physicsSimulators/physicsSimulator.s"
	@echo "... stdInclude/stdInclude.o"
	@echo "... stdInclude/stdInclude.i"
	@echo "... stdInclude/stdInclude.s"
	@echo "... visualizer/visualizer.o"
	@echo "... visualizer/visualizer.i"
	@echo "... visualizer/visualizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

