set(_CATKIN_CURRENT_PACKAGE "physicsSimSwitching")
set(physicsSimSwitching_VERSION "0.0.0")
set(physicsSimSwitching_MAINTAINER "davidrussell <davidrussell@todo.todo>")
set(physicsSimSwitching_PACKAGE_FORMAT "2")
set(physicsSimSwitching_BUILD_DEPENDS )
set(physicsSimSwitching_BUILD_EXPORT_DEPENDS )
set(physicsSimSwitching_BUILDTOOL_DEPENDS "catkin")
set(physicsSimSwitching_BUILDTOOL_EXPORT_DEPENDS )
set(physicsSimSwitching_EXEC_DEPENDS )
set(physicsSimSwitching_RUN_DEPENDS )
set(physicsSimSwitching_TEST_DEPENDS )
set(physicsSimSwitching_DOC_DEPENDS )
set(physicsSimSwitching_URL_WEBSITE "")
set(physicsSimSwitching_URL_BUGTRACKER "")
set(physicsSimSwitching_URL_REPOSITORY "")
set(physicsSimSwitching_DEPRECATED "")